
<?php 
$title = 'Add new IP';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('monitor', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('ip'));
 echo $this->formhidden($form->get('added'));
 echo $this->formSubmit($form->get('add_ip'));
 echo $this->form()->closeTag();